name: continuous-integration-example

on:
  push:
    branches:
      - main

jobs:
  build-and-test-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build with Gradle!
        working-directory: .
        run: ./gradlew build -x test

      - name: Run tests, please!
        working-directory: .
        run: ./gradlew test
